<a href="https://colab.research.google.com/github/pavan9753/Breast_Cancer_Detection/blob/main/Breast_Cancer_Detection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [87]:

#Importing the required packages
import  pandas as pd
import numpy as np
# Importing the dataset which is already predefined in sklearn.datasets
from sklearn.datasets import load_breast_cancer
#Importing pandas
from sklearn.preprocessing import StandardScaler
from keras.models import Sequential
from keras.layers import Dense

In [94]:


#Loading data into the a variable
data=load_breast_cancer()
#printing data ,It is in the form of  a (key,value) pair
data

{'DESCR': '.. _breast_cancer_dataset:\n\nBreast cancer wisconsin (diagnostic) dataset\n--------------------------------------------\n\n**Data Set Characteristics:**\n\n    :Number of Instances: 569\n\n    :Number of Attributes: 30 numeric, predictive attributes and the class\n\n    :Attribute Information:\n        - radius (mean of distances from center to points on the perimeter)\n        - texture (standard deviation of gray-scale values)\n        - perimeter\n        - area\n        - smoothness (local variation in radius lengths)\n        - compactness (perimeter^2 / area - 1.0)\n        - concavity (severity of concave portions of the contour)\n        - concave points (number of concave portions of the contour)\n        - symmetry \n        - fractal dimension ("coastline approximation" - 1)\n\n        The mean, standard error, and "worst" or largest (mean of the three\n        largest values) of these features were computed for each image,\n        resulting in 30 features.  For

In [95]:

#Printing the keys present in the data
data.keys()



dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names', 'filename'])

In [19]:
print(data['DESCR'])

.. _breast_cancer_dataset:

Breast cancer wisconsin (diagnostic) dataset
--------------------------------------------

**Data Set Characteristics:**

    :Number of Instances: 569

    :Number of Attributes: 30 numeric, predictive attributes and the class

    :Attribute Information:
        - radius (mean of distances from center to points on the perimeter)
        - texture (standard deviation of gray-scale values)
        - perimeter
        - area
        - smoothness (local variation in radius lengths)
        - compactness (perimeter^2 / area - 1.0)
        - concavity (severity of concave portions of the contour)
        - concave points (number of concave portions of the contour)
        - symmetry 
        - fractal dimension ("coastline approximation" - 1)

        The mean, standard error, and "worst" or largest (mean of the three
        largest values) of these features were computed for each image,
        resulting in 30 features.  For instance, field 3 is Mean Radius, f

In [18]:

print(data['target_names'])

['malignant' 'benign']


In [22]:
data['data'].shape
data['feature_names']

array(['mean radius', 'mean texture', 'mean perimeter', 'mean area',
       'mean smoothness', 'mean compactness', 'mean concavity',
       'mean concave points', 'mean symmetry', 'mean fractal dimension',
       'radius error', 'texture error', 'perimeter error', 'area error',
       'smoothness error', 'compactness error', 'concavity error',
       'concave points error', 'symmetry error',
       'fractal dimension error', 'worst radius', 'worst texture',
       'worst perimeter', 'worst area', 'worst smoothness',
       'worst compactness', 'worst concavity', 'worst concave points',
       'worst symmetry', 'worst fractal dimension'], dtype='<U23')

In [98]:

#Converting the data['data] to a data frame for better understanding
df=pd.DataFrame(data['data'],columns=data['feature_names'])
df.head()

mean radius  mean texture  ...  worst symmetry  worst fractal dimension
0        17.99         10.38  ...          0.4601                  0.11890
1        20.57         17.77  ...          0.2750                  0.08902
2        19.69         21.25  ...          0.3613                  0.08758
3        11.42         20.38  ...          0.6638                  0.17300
4        20.29         14.34  ...          0.2364                  0.07678

[5 rows x 30 columns]

In [99]:
#analysing the first one of 569 cancers given
k=0
for i in data['feature_names']:
  print(i,": ",data['data'][0][k])
  k+=1

mean radius :  17.99
mean texture :  10.38
mean perimeter :  122.8
mean area :  1001.0
mean smoothness :  0.1184
mean compactness :  0.2776
mean concavity :  0.3001
mean concave points :  0.1471
mean symmetry :  0.2419
mean fractal dimension :  0.07871
radius error :  1.095
texture error :  0.9053
perimeter error :  8.589
area error :  153.4
smoothness error :  0.006399
compactness error :  0.04904
concavity error :  0.05373
concave points error :  0.01587
symmetry error :  0.03003
fractal dimension error :  0.006193
worst radius :  25.38
worst texture :  17.33
worst perimeter :  184.6
worst area :  2019.0
worst smoothness :  0.1622
worst compactness :  0.6656
worst concavity :  0.7119
worst concave points :  0.2654
worst symmetry :  0.4601
worst fractal dimension :  0.1189


In [100]:
data['target_names']
feature=data['data']
label=data['target']



In [101]:
print(data['target'].shape)
print(data['target'])


(569,)
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 1 0 0 0 0 0 0 0 0 1 0 1 1 1 1 1 0 0 1 0 0 1 1 1 1 0 1 0 0 1 1 1 1 0 1 0 0
 1 0 1 0 0 1 1 1 0 0 1 0 0 0 1 1 1 0 1 1 0 0 1 1 1 0 0 1 1 1 1 0 1 1 0 1 1
 1 1 1 1 1 1 0 0 0 1 0 0 1 1 1 0 0 1 0 1 0 0 1 0 0 1 1 0 1 1 0 1 1 1 1 0 1
 1 1 1 1 1 1 1 1 0 1 1 1 1 0 0 1 0 1 1 0 0 1 1 0 0 1 1 1 1 0 1 1 0 0 0 1 0
 1 0 1 1 1 0 1 1 0 0 1 0 0 0 0 1 0 0 0 1 0 1 0 1 1 0 1 0 0 0 0 1 1 0 0 1 1
 1 0 1 1 1 1 1 0 0 1 1 0 1 1 0 0 1 0 1 1 1 1 0 1 1 1 1 1 0 1 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 1 1 1 1 1 1 0 1 0 1 1 0 1 1 0 1 0 0 1 1 1 1 1 1 1 1 1 1 1 1
 1 0 1 1 0 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 0 1 0 1 1 1 1 0 0 0 1 1
 1 1 0 1 0 1 0 1 1 1 0 1 1 1 1 1 1 1 0 0 0 1 1 1 1 1 1 1 1 1 1 1 0 0 1 0 0
 0 1 0 0 1 1 1 1 1 0 1 1 1 1 1 0 1 1 1 0 1 1 0 0 1 1 1 1 1 1 0 1 1 1 1 1 1
 1 0 1 1 1 1 1 0 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 0 1 0 0 1 0 1 1 1 1 1 0 1 1
 0 1 0 1 1 0 1 0 1 1 1 1 1 1 1 1 0 0 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 0 1
 1 1 1 1 1 1 0 1 0

In [33]:
data['filename']

'/usr/local/lib/python3.7/dist-packages/sklearn/datasets/data/breast_cancer.csv'

In [36]:
print(feature)
print(label)

[[1.799e+01 1.038e+01 1.228e+02 ... 2.654e-01 4.601e-01 1.189e-01]
 [2.057e+01 1.777e+01 1.329e+02 ... 1.860e-01 2.750e-01 8.902e-02]
 [1.969e+01 2.125e+01 1.300e+02 ... 2.430e-01 3.613e-01 8.758e-02]
 ...
 [1.660e+01 2.808e+01 1.083e+02 ... 1.418e-01 2.218e-01 7.820e-02]
 [2.060e+01 2.933e+01 1.401e+02 ... 2.650e-01 4.087e-01 1.240e-01]
 [7.760e+00 2.454e+01 4.792e+01 ... 0.000e+00 2.871e-01 7.039e-02]]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 1 0 0 0 0 0 0 0 0 1 0 1 1 1 1 1 0 0 1 0 0 1 1 1 1 0 1 0 0 1 1 1 1 0 1 0 0
 1 0 1 0 0 1 1 1 0 0 1 0 0 0 1 1 1 0 1 1 0 0 1 1 1 0 0 1 1 1 1 0 1 1 0 1 1
 1 1 1 1 1 1 0 0 0 1 0 0 1 1 1 0 0 1 0 1 0 0 1 0 0 1 1 0 1 1 0 1 1 1 1 0 1
 1 1 1 1 1 1 1 1 0 1 1 1 1 0 0 1 0 1 1 0 0 1 1 0 0 1 1 1 1 0 1 1 0 0 0 1 0
 1 0 1 1 1 0 1 1 0 0 1 0 0 0 0 1 0 0 0 1 0 1 0 1 1 0 1 0 0 0 0 1 1 0 0 1 1
 1 0 1 1 1 1 1 0 0 1 1 0 1 1 0 0 1 0 1 1 1 1 0 1 1 1 1 1 0 1 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 1 1 1 1 1 1 0 1 0 1 1 0 1 1 0 1 0 0 1 1 1 1 1 1 1 1 

In [103]:
#StandardScaler function for transforming all the values into a smaller range
scale=StandardScaler()
feature=scale.fit_transform(feature)
k=0
for i in data['feature_names']:
  print(i,": ",feature[0][k])
  k+=1

mean radius :  1.097063981469985
mean texture :  -2.0733350146975855
mean perimeter :  1.269933688139939
mean area :  0.9843749048031146
mean smoothness :  1.568466329243421
mean compactness :  3.28351467098683
mean concavity :  2.6528739837431687
mean concave points :  2.5324752164032422
mean symmetry :  2.2175150059646414
mean fractal dimension :  2.255746885296271
radius error :  2.489733926737622
texture error :  -0.565265059068463
perimeter error :  2.833030865855182
area error :  2.4875775569611047
smoothness error :  -0.21400164666895324
compactness error :  1.316861568395947
concavity error :  0.7240261580803592
concave points error :  0.6608199414286061
symmetry error :  1.1487566671861764
fractal dimension error :  0.9070830809973358
worst radius :  1.8866896251792782
worst texture :  -1.3592934737640856
worst perimeter :  2.3036006236225615
worst area :  2.0012374893299207
worst smoothness :  1.3076862710715431
worst compactness :  2.616665023512605
worst concavity :  2.1095

In [104]:
#Converting the faeture to a data frame for better understanding
df=pd.DataFrame(feature,columns=data['feature_names'])
df.head()


mean radius  mean texture  ...  worst symmetry  worst fractal dimension
0     1.097064     -2.073335  ...        2.750622                 1.937015
1     1.829821     -0.353632  ...       -0.243890                 0.281190
2     1.579888      0.456187  ...        1.152255                 0.201391
3    -0.768909      0.253732  ...        6.046041                 4.935010
4     1.750297     -1.151816  ...       -0.868353                -0.397100

[5 rows x 30 columns]

In [105]:
#Now divide the dataset into training,validation and testing purposes
# 80%---Training the model(500 samples)
# 10%---Validating the model(35 samples)
# 10%---Testing the model(34 samples)
#------------------------------------#
#Training
X_train=feature[0:500]
Y_train=label[0:500]
#Validating
X_val=feature[500:535]
Y_val=label[500:535]
#Training
X_test=feature[535:]
Y_test=label[535:]



In [106]:
#Printing the shape of each division
print(X_train.shape)
print(X_train.shape)
print(X_val.shape)
print(Y_val.shape)
print(X_test.shape)
print(Y_test.shape)


(500, 30)
(500, 30)
(35, 30)
(35,)
(34, 30)
(34,)


In [107]:
#Sequential for connecting the weights of input,hidden,output layers
model=Sequential()

In [109]:
#Adding the layers with add function to model
#Relu function used to transfer the information same as our neurons
model.add(Dense(15,activation='relu',input_dim=30))
model.add(Dense(15,activation='relu'))
#Sigmoid function used to generate the output value in between 0 and 1,as we have to output the type of cancer name
model.add(Dense(1,activation='sigmoid'))
#compile the model
#adam optimizer is used to tune the weigthts in an optimized way so that our model's accuracy is to be high
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])



In [110]:
# 1 Epoch--Traversing(Giving) the whole dataset once
model.fit(X_train,Y_train,epochs=20,validation_data=(X_val,Y_val))

Epoch 1/20
16/16 [==============================] - 1s 12ms/step - loss: 0.8859 - accuracy: 0.5520 - val_loss: 0.7208 - val_accuracy: 0.5714
Epoch 2/20
16/16 [==============================] - 0s 4ms/step - loss: 0.6202 - accuracy: 0.6540 - val_loss: 0.5505 - val_accuracy: 0.7429
Epoch 3/20
16/16 [==============================] - 0s 3ms/step - loss: 0.4556 - accuracy: 0.8180 - val_loss: 0.4244 - val_accuracy: 0.8857
Epoch 4/20
16/16 [==============================] - 0s 3ms/step - loss: 0.3556 - accuracy: 0.9060 - val_loss: 0.3398 - val_accuracy: 0.9143
Epoch 5/20
16/16 [==============================] - 0s 3ms/step - loss: 0.2897 - accuracy: 0.9140 - val_loss: 0.2757 - val_accuracy: 0.9429
Epoch 6/20
16/16 [==============================] - 0s 4ms/step - loss: 0.2422 - accuracy: 0.9320 - val_loss: 0.2265 - val_accuracy: 0.9429
Epoch 7/20
16/16 [==============================] - 0s 3ms/step - loss: 0.2059 - accuracy: 0.9380 - val_loss: 0.1900 - val_accuracy: 0.9429
Epoch 8/20
16/16 [=

In [111]:
#evaluate the final test results
model.evaluate(X_test,Y_test)

2/2 [==============================] - 0s 7ms/step - loss: 0.1173 - accuracy: 0.9706


[0.11728843301534653, 0.970588207244873]

In [112]:
sample=X_test[0]

In [88]:
sample=np.reshape(sample,(1,30))

In [89]:
sample.shape

(1, 30)

In [114]:

#Check for the results predicted by our model and the actual values
for i in range(34):
  sample=X_test[i]
  sample=np.reshape(sample,(1,30))
  if(model.predict(sample)[0][0]>0.5):
    print("-Benign")
  else:
    print("-Malignant")
  if(Y_test[i]==0):
    print("*Malignant")
  else:
    print("*Benign")
  print("--------------------")

  


-Malignant
*Malignant
--------------------
-Malignant
*Malignant
--------------------
-Benign
*Benign
--------------------
-Benign
*Benign
--------------------
-Benign
*Benign
--------------------
-Benign
*Benign
--------------------
-Malignant
*Benign
--------------------
-Benign
*Benign
--------------------
-Benign
*Benign
--------------------
-Benign
*Benign
--------------------
-Benign
*Benign
--------------------
-Benign
*Benign
--------------------
-Benign
*Benign
--------------------
-Benign
*Benign
--------------------
-Benign
*Benign
--------------------
-Benign
*Benign
--------------------
-Benign
*Benign
--------------------
-Benign
*Benign
--------------------
-Benign
*Benign
--------------------
-Benign
*Benign
--------------------
-Benign
*Benign
--------------------
-Benign
*Benign
--------------------
-Benign
*Benign
--------------------
-Benign
*Benign
--------------------
-Benign
*Benign
--------------------
-Benign
*Benign
--------------------
-Benign
*Benign
-------